### ISSUE TITLE
I am executing sample watson project so that getting issue "Error: Cannot find module 'botium-core'

### ISSUE THREAD

**Issue by stephenws** [codeforequity-at/botium-connector-watson#1]
PS E:\botium-connector-watson-master\botium-connector-watson-master\samples> node botiumFluent.js
module.js:550
    throw err;
    ^

Error: Cannot find module 'botium-core'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\botium-connector-watson-master\botium-connector-watson-master\samples\botiumFluent.js:1:81)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
PS E:\botium-connector-watson-master\botium-connector-watson-master\samples>

**Comment by codeforequity-at** [comment]
please run "npm install" first for preparation (in main folder and in samples folder)
